### PR TITLE
Expose buffer for inspection and manipulation

### PR DESCRIPTION
**Pull request by tjconcept**

### CODE REVIEW

**Comment by dominictarr** [comment]
can you explain how you are using this or show me code that uses this?

**Comment by tjconcept** [comment]
I'm using this for relaying events to sockets. Events are produced in real-time all over the application. A consumer (a socket) might be slow or have delays.
If the buffer increases above a certain treshold I would like to issue a warning and eventually drop the socket as being disconnected. Comparing buffer sizes across sockets can help detect if a network issue is on the application or specific to a socket.

**Comment by tjconcept** [comment]
This is analogue to https://nodejs.org/api/net.html#net_socket_buffersize, and for the same reasons/use cases, I suppose.

**Comment by dominictarr** [comment]
merged into 2.2.0

**Pull request merged**
